# Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
b = np.array([[1,2,3],[4,5,6]])

In [5]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
#Get Dimensions
a.ndim

1

In [7]:
b.ndim

2

In [8]:
#Get Shape
a.shape

(3,)

In [9]:
b.shape

(2, 3)

In [10]:
#Get Size
a.size

3

In [11]:
b.size

6

In [14]:
#Get Total Size
a.nbytes

12

In [15]:
b.nbytes

24

# Accessing/Changing elements, rows, columns

In [27]:
c = np.array([[1,2,3,4,5,6,7],[7,8,9,1,4,5,3]])
print(c)

[[1 2 3 4 5 6 7]
 [7 8 9 1 4 5 3]]


In [19]:
#get a specific element [r,c]
c[1,3]

1

In [20]:
#Get a specific row
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
#Get a specific columns
c[:,2]

array([3, 9])

In [23]:
#Getting a little fancy [startindex:endindex;stepsize]
c[0,1:6:2]

array([2, 4, 6])

In [28]:
c[0,2]=1
print(c)

[[1 2 1 4 5 6 7]
 [7 8 9 1 4 5 3]]


In [30]:
c[:,2]=[3,4]
print(c)

[[1 2 3 4 5 6 7]
 [7 8 4 1 4 5 3]]


# 3-D Example

In [34]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [35]:
#Get specific element (work outside in)
d[0,1,1]

4

In [36]:
d[:,1,:]

array([[3, 4],
       [7, 8]])

In [39]:
d[:,0,:] = [[1,1],[1,1]]
print(d)

[[[1 1]
  [3 4]]

 [[1 1]
  [7 8]]]


# Initializing DIfferent types of Arrays

In [48]:
#All 0s Matrix
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [49]:
#All 1s Matrix
np.ones((2,4,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [51]:
#ANy other number
np.full((2,3),100)

array([[100, 100, 100],
       [100, 100, 100]])

In [53]:
#Any other number (full_like)
np.full_like(d,4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [55]:
#Random Decimal Numbers
np.random.rand(4,2)

array([[0.11965556, 0.39614991],
       [0.53851517, 0.35221323],
       [0.06495275, 0.05574944],
       [0.4830446 , 0.89811886]])

In [63]:
#Random Integer Values
np.random.randint(3,5, size=(3,3))

array([[3, 4, 3],
       [4, 3, 4],
       [4, 3, 3]])

In [65]:
#The identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [70]:
#Repeat an Array
e = np.array([1,2,3])
r1 = np.repeat(e,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [72]:
#Repeat an array
e = np.array([[1,2,3]])
r1 = np.repeat(e,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [80]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
print(z)

output[1:4,1:4] = z
print(output)

output[2,2] = 9
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be Carefull When Copying variable

In [84]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


# Mathematics

In [99]:
f = np.array([1,2,3,4,5])
print(f)

[1 2 3 4 5]


In [88]:
f+2

array([3, 4, 5, 6, 7])

In [89]:
f-2

array([-1,  0,  1,  2,  3])

In [90]:
f*2

array([ 2,  4,  6,  8, 10])

In [91]:
f/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [92]:
f//2

array([0, 1, 1, 2, 2], dtype=int32)

In [93]:
f%2

array([1, 0, 1, 0, 1], dtype=int32)

In [98]:
f**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [100]:
g = np.array([1,0,1,0,1])
f+g

array([2, 2, 4, 4, 6])

In [101]:
#take the sin/cos/tan
np.cos(f)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

Linear Algebra

In [107]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [108]:
#find the diterminant
c = np.identity(3)
np.linalg.det(c)

1.0

Statistics

In [113]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [120]:
np.min(stats, axis=0)

array([1, 2, 3])

In [121]:
np.max(stats, axis=0)

array([4, 5, 6])

In [123]:
np.sum(stats,axis=0)

array([5, 7, 9])

# Reorganizing Arrays

In [129]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape(4,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [134]:
#Verticaly Stacking Vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [135]:
#Horizontal Stacking Vectors
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

# Miscellaneos

Load Data From File

In [144]:
filedata = np.genfromtxt('data.txt', delimiter = ',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

Masking and Advanced indexing

In [147]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [151]:
np.all(filedata>50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [154]:
(~((filedata >50) & (filedata<100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])